name: Unit-test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle.kts'
  push:
    branches:
      - 'master'
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle.kts'

jobs:
  Unit-test:
    name: Run unit tests on PR in master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create google-sevices.json
        run: cat /home/runner/work/LFilms/LFilms/app/google-services.json | base64

      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/LFilms/LFilms/app/google-services.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle tests
        run: ./gradlew test
